export const sports = [
  "soccer",
  "basketball",
  "baseball",
  "football",
  "rugby",
  "cricket",
  "tennis",
  "table tennis",
  "badminton",
  "squash",
  "volleyball",
  "beach volleyball",
  "handball",
  "field hockey",
  "ice hockey",
  "golf",
  "boxing",
  "wrestling",
  "swimming",
  "diving",
  "water polo",
  "rowing",
  "mountain biking",
  "triathlon",
  "gymnastics",
  "surfing",
] as const;

export type SportType = (typeof sports)[number];
